-- One-time seed: loads your existing procedure list into the new shared master_procedures table.
-- Run this once in D1 Console after creating the table.

INSERT INTO master_procedures (code, name, rate) VALUES ('D1001', 'Intraoral Periapical (IOPA) Radiograph X-ray/RVG(Single Film)', 153.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('D1002', 'Intraoral Occlusal/Bite Wing X-Ray', 230.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('D1003', 'Digital OPG with X ray film/ CD', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('D1004', 'Biopsy of Oral tissue - Soft', 918.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('D1005', 'Biopsy of Oral tissue - Hard (bone, tooth)', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP001', 'Abscess - Drainage-Dental', 1148.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP002', 'Scaling', 765.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP003', 'Curettage and Root Planning Per Tooth', 268.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP004', 'Curettage and Root Planning - Per Arch', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP005', 'Gingivoplasty - Per Quadrant', 765.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP006', 'Gingivectomy - Per Quadrant', 918.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP007', 'Flap Surgery- Per Tooth', 344.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP008', 'Flap Surgery- Per Quadrant', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP009', 'Flap Surgery and Bone Graft per quadrant', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP010', 'Extraction - Normal Tooth', 306.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP011', 'Complicated Extraction per tooth under LA', 612.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP012', 'Extraction Impacted - Soft tissue/3rd Molar/Wisdom Tooth', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP013', 'Multiple Extraction for Special Children/GA Cases', 4590.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP014', 'Extraction - Orthodontic Extraction', 574.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP015', 'Operculectomy - Pericoronal Flap Excision', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP016', 'Extraction Impacted - Bony', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP017', 'Alveoloplasty - Per Tooth', 230.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP018', 'Alveoloplasty - Per Quadrant', 918.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP019', 'Frenectomy', 1913.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP020', 'Excision of hyperplastic tissue per arch', 918.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP021', 'Surgical Augmentation / Alveolectomy per Arch', 2678.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP022', 'Bone Replacement Graft for Ridge Preservation - per site', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP023', 'Minor oral surgery (Cyst, Granuloma, Mucocele, Epulis) under LA', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP024', 'Application of Desensitizing Medicament', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP025', 'Fluoride Application for Children', 765.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP026', 'Temporary restoration', 115.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP027', 'Glass ionomer Cement Restoration', 459.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP028', 'Composite Occlusal Pit / Class I Restoration', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP029', 'Composite - Class II / III / IV / MOD / Diastema Closure', 765.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP030', 'Root Canal Treatment - Single Rooted Tooth', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP031', 'Root Canal Treatment - Multi-Rooted Tooth', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP032', 'Re-RCT (Anterior Tooth)', 1913.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP033', 'Re-RCT (Posterior Tooth)', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP034', 'Intracanal Medicament (for periapical lesion)', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP035', 'Apicectomy – Single Tooth', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP036', 'Apicectomy – Multiple Teeth', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP037', 'Apexification with bio-compatible material', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP038', 'Root-end resection and Retrograde Filling', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP039', 'Surgical Apicectomy/Periapical surgery without grafting', 536.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP040', 'Tissue Conditioning – Maxillary/Mandibular', 230.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP041', 'Core Build-Up / Post & Core – Custom made / Inlay / Onlay', 1148.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP042', 'Crown Lengthening – Per Tooth', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP043', 'Crown – PMMA Crown (Temporary)', 765.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP044', 'Crown – All-Metal (Nickel-Free)', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP045', 'Crown – Metal with Ceramic Facing (PFM)', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP046', 'Crown Re-cementation', 459.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP047', 'Crown Removal', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP048', 'Odontoplasty / Enameloplasty', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP049', 'Pulpectomy (Anterior Tooth)', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP050', 'Pulpectomy (Posterior Tooth)', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP051', 'Pulpotomy', 765.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP052', 'Veneer – Ceramic (Pediatric)', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP053', 'Interceptive Orthodontic Treatment – Primary / Transitional Dentition', 5355.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP054', 'Limited Orthodontic Treatment – Primary Dentition', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP055', 'Occlusion Analysis / Occlusal Equilibration', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP056', 'Tooth Splinting – General', 1148.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP057', 'Splinting – Periodontally Weak Teeth', 1377.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP058', 'Night Guard', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP059', 'Bridge / Fixed Partial Denture (per missing tooth – Metal)', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP060', 'Bridge / Fixed Partial Denture (per missing tooth – PFM)', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP061', 'Removable Partial Denture – Flexible (Per Arch)', 5738.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP062', 'Removable Partial Denture – Cast Metal (up to 3 Teeth)', 3060.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP063', 'Removable Partial Denture – Cast Metal (additional per Tooth)', 230.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP064', 'Removable Partial Denture – Acrylic (up to 3 Teeth)', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP065', 'Removable Partial Denture – Tooth Addition (per Tooth)', 230.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP066', 'Add Clasp to existing Partial Denture', 383.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP067', 'Add Tooth to existing Partial Denture', 306.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP068', 'Tooth Supported Overdenture (Per Arch)', 5738.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP069', 'Complete Denture (Per Arch)', 7650.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP070', 'Removable Orthodontic Appliance / Post-Orthodontic ROA – Per Arch', 1913.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP071', 'Fixed Orthodontic Treatment – Per Arch', 11475.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP072', 'Space Maintainers – Fixed', 3060.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP073', 'Habit-Breaking Appliance (Removable)', 1913.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP074', 'Odontoplasty / Enameloplasty – Recontouring', 3060.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP075', 'Pulpectomy (Anterior Tooth – Pediatric)', 4590.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP076', 'Pulpectomy (Posterior Tooth – Pediatric)', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP077', 'Pulpotomy – Pediatric', 4973.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP078', 'Veneer – Ceramic (Pediatric)', 5355.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP079', 'Interceptive Orthodontic Treatment – Mixed Dentition', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP080', 'Limited Orthodontic Treatment – Transitional Dentition', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP081', 'Occlusal Adjustment / Equilibration – Pediatric', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP082', 'Tooth Splinting – General (Pediatric)', 11475.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP083', 'Splinting – Periodontally Weak Teeth (Pediatric)', 14535.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP084', 'Facial Space Abscess – Drainage', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP085', 'Partial Ostectomy / Sequestrectomy for Removal of Non-vital Bone', 1530.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP086', 'Closed Reduction – Stabilization of Teeth (Alveolus)', 3060.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP087', 'Open Reduction – Stabilization of Teeth (Alveolus)', 4590.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP088', 'Arch Bar Fixation', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP089', 'Oro-antral Fistula Closure', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP090', 'Osseous / Osteoperiosteal / Cartilage Graft – Mandible or Maxilla', 2295.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP091', 'Osteoplasty – Orthognathic Deformities / Mandibular Rami / Body of Mandible', 21803.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP092', 'Maxilla – Closed Reduction', 4590.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP093', 'Maxilla – Open Reduction', 7650.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP094', 'Mandible – Closed Reduction', 4590.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP095', 'Mandible – Open Reduction', 7650.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP096', 'Cyst of Maxilla / Mandible – Enucleation / Excision ≤ 4 cm (LA)', 3825.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP097', 'Cyst of Maxilla / Mandible – Enucleation / Excision > 4 cm (LA)', 4590.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP098', 'Cyst of Maxilla / Mandible – Enucleation / Excision > 4 cm (GA)', 18169.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP099', 'Cyst of Maxilla / Mandible – Enucleation / Excision > 4 cm (GA + Admission)', 14535.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP100', 'Segmental / Hemi-mandibulectomy with Graft', 18169.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP101', 'Segmental / Hemi-mandibulectomy without Graft', 14535.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP102', 'Sub-total Mandibulectomy with Graft', 25436.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP103', 'Sub-total Mandibulectomy without Graft', 21803.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP104', 'Maxillectomy / Mandibulectomy – Total with Graft', 25436.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP105', 'Maxillectomy / Mandibulectomy – Total without Graft', 21803.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP106', 'Maxillectomy – Partial with Graft', 18169.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP107', 'Maxillectomy – Partial without Graft', 14535.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP108', 'Malar / Zygomatic Arch – Closed Reduction', 4590.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP109', 'Malar / Zygomatic Arch – Open Reduction', 7650.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP110', 'Distraction Osteogenesis – Mandible or Maxilla (GA)', 21803.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('DP111', 'Facial Bones – Complicated Reduction with Fixation', 32704.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('CN001', 'Consultation / OPD Visit', 350.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK001', 'Consultation / OPD Visit', 350.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK002', 'X RAY / J K IOPA DIGITAL', 200.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK003', 'ORAL PROPHYLAXIS', 2800.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK004', 'RCT', 3500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK005', 'COMPOSITE RESTORATION', 800.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK006', 'GIC RESTORATION', 800.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK007', 'PORCELAIN CROWN', 3000.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK008', 'VITA PFM CROWN', 3500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK009', 'IVOCLAR PFM CROWN', 4500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK010', 'ZIRCONIA CROWN', 8500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK011', 'ZIRCONIA PLUS CROWN', 12000.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK012', 'ACRYLIC CROWN', 1500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK013', 'EXTRACTION NORMAL', 850.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK014', 'EXTRACTION SURGICAL', 1250.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK015', 'EXTRACTION SURGICAL THIRD MOLAR', 2500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK016', 'EXTRACTION IMPACTED THIRD MOLAR', 4000.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK017', 'EXTRACTION SURGICAL HORIZONTAL THIRD MOLAR', 6500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
INSERT INTO master_procedures (code, name, rate) VALUES ('JK018', 'EXTRACTION SURGICAL ORTHODONTIC', 2500.00) ON CONFLICT(code) DO UPDATE SET name=excluded.name, rate=excluded.rate;
