-- One-time seed: loads the existing medicine list into the new shared master_medicines table.
-- Run this once in D1 Console after creating the table.

INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab MOXIND CV 625');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab MOXIND CV 375');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab CLAVUM 625');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab BLESSMOX CV 625');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab AUGMENTIN 625');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab AUGMENTIN 375');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab CEFTUM 500');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab CEFAKIND 250');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'GUDCEF 200');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab LEVOFLOX 500');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab ZENFLOX OZ');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab CIPROFLOX 500');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab METROGYL ER');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab METROGYL 400');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab HYFENAC P');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab FLOZEN PLUS');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab JIYAGESIC P');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab COMBIFLAME');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab ULTRACET');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab ACECLOFENAC +PARACETAMOL');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab ACEFLAME P');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab NIMUSULIDE PARACTAMOL');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab DOLOKIND PLUS');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab DOLOKIND AA');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab DICLOFENAC+PCM');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab NOBEL MR');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab PANTOP D');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab PANTAKIND DSR');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab RANITIDINE 150/300');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab ACELOC 300');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab CHYMORAL FORT');
INSERT INTO master_medicines (category, name) VALUES ('TAB', 'Tab CLONAFIT 0.25 mg 1 TAB SOS/hs');
INSERT INTO master_medicines (category, name) VALUES ('CAP', 'Cap OMEPRAZOLE');
INSERT INTO master_medicines (category, name) VALUES ('CAP', 'Cap VIZYLZC');
INSERT INTO master_medicines (category, name) VALUES ('SYP', 'Syp AUGMENTIN');
INSERT INTO master_medicines (category, name) VALUES ('SYP', 'Syp IBUGESIC P');
INSERT INTO master_medicines (category, name) VALUES ('MOUTHWASH', 'BETADINE GARGLE');
INSERT INTO master_medicines (category, name) VALUES ('MOUTHWASH', 'BETAKIND GARGLE');
INSERT INTO master_medicines (category, name) VALUES ('MOUTHWASH', 'THERMOKIND MOUTH WASH');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'ORNIGRATE GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'METROGYLDG GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'HEXIMETRO GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'ORAWAYS GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'TURBOCORT GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'KENACORT GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'TESS GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'MUCOPAIN GEL');
INSERT INTO master_medicines (category, name) VALUES ('GEL', 'SENOLIN SF GEL');
INSERT INTO master_medicines (category, name) VALUES ('FLOSS', 'THERMOKIND TOOTHPASTE');
INSERT INTO master_medicines (category, name) VALUES ('FLOSS', 'THERMOSEAL DENTAL FLOSS');
INSERT INTO master_medicines (category, name) VALUES ('FLOSS', 'THERMOSEAL PROXA BRUSH');
